export const SLUG_HEADER_STYLES = {
	wrapper: {
		position: "fixed",
		top: 0,
		zIndex: 100,
		w: "full",
		backgroundSize: "cover",
		backgroundPosition: "top center",
		boxShadow: "0 8px 24px -4px rgba(0, 0, 0, 0.5)",
		pb: 0,
		transition: "all 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
		overflow: "hidden",
		bg: "rgba(255, 255, 255, 0.45)",
		backdropFilter: "blur(1.5px) saturate(110%)",
		h: "auto",
		"&[data-scrolled='true']": {
			backdropFilter: "none",
			h: "110px",
		},
	},

	leftActions: {
		position: "absolute",
		top: 3,
		left: 4,
		zIndex: 10,
	},

	rightLogo: {
		position: "absolute",
		top: 3,
		right: 6,
		zIndex: 10,
		w: "max-content",
		opacity: 1,
		pointerEvents: "auto",
		transform: "scale(0.4)",
		transformOrigin: "top right",
		transition: "all 0.4s ease",
	},

	centerFlex: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		w: "full",
		h: "full",
		position: "relative",
		pt: { base: "50px", md: 3 },
		"[data-scrolled='true'] &": {
			pt: 0,
		},
	},

	mainLogoWrapper: {
		position: "relative",
		pointerEvents: "auto",
		opacity: 1,
		transform: "translateY(0) scale(1)",
		transition: "all 0.4s ease",
		"[data-scrolled='true'] &": {
			position: "absolute",
			pointerEvents: "none",
			opacity: 0,
			transform: "translateY(-20px) scale(0.8)",
		},
	},

	scrolledLogoWrapper: {
		position: "absolute",
		top: 16,
		right: 6,
		transformOrigin: "top right",
		pointerEvents: "none",
		opacity: 0,
		transform: "scale(0)",
		transition: "all 0.4s ease",
		"[data-scrolled='true'] &": {
			pointerEvents: "auto",
			opacity: 1,
			transform: "scale(0.6)",
		},
	},

	categoryTitle: {
		color: "#641615",
		fontSize: { base: "2sm", sm: "2md", md: "2lg", lg: "2xl" },
		fontWeight: "bold",
		fontFamily: "quicksand",
		textTransform: "uppercase",
		textDecoration: "underline",
		textUnderlineOffset: "6px",
		textDecorationThickness: "2px",
		letterSpacing: "wide",
		lineHeight: "1",
		pb: "6px",
		mb: "-1px",
		transition: "all 0.4s ease",
		mt: 7,
		"[data-scrolled='true'] &": {
			mt: 2,
		},
	},

	postTitle: {
		color: "#641615",
		fontSize: { base: "xl", md: "3xl", lg: "4xl" },
		fontWeight: "bold",
		textTransform: "uppercase",
		position: "absolute",
		pointerEvents: "none",
		opacity: 0,
		transform: "translateY(20px)",
		transition: "all 0.4s ease",
		mt: 2,
		"[data-scrolled='true'] &": {
			position: "relative",
			pointerEvents: "auto",
			opacity: 1,
			transform: "translateY(0)",
		},
	},
};